ktor {
    deployment {
        port = 8080
        port = ${?PORT}
        host = "0.0.0.0"
    }
    application {
        modules = [ com.example.ApplicationKt.main ]
    }
}

# Development environment settings
logging.level = "DEBUG"
app {
    environment = "development"
}