ktor {
    deployment {
        port = 8080
        port = ${?PORT}
        host = "0.0.0.0"
    }
    application {
        modules = [ com.example.ApplicationKt.main ]
    }
}

# Production environment settings
logging.level = "INFO"
app {
    environment = "production"
}