ktor {
    deployment {
        port = 8081
        port = ${?PORT}
        host = "127.0.0.1"
    }
    application {
        modules = [ com.example.ApplicationKt.main ]
    }
}

# Test environment settings
logging.level = "WARN"
app {
    environment = "test"
}